name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install everything else
      - name: Install other dependencies
        run: |
          pip install -r requirements_jupyter.txt
      - name: Install localtileserver
        run: pip install -e .
      - name: Scooby Report
        run: python -c "import localtileserver;print(localtileserver.Report())"
      - name: Run Tests
        run: |
          pytest -v --cov=localtileserver
          coverage xml -o coverage.xml
      # - name: Run Doc Tests
      #   run: |
      #     make doctest
      - name: Stash coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage.xml
          path: coverage.xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          verbose: true
